#!/usr/bin/env dash

# Custom Dockerfile init script. 
# Copies files, sets UID/GID, applies time zone, starts supervisor.

# Copy crontab files into container as root-owned.
cp --no-preserve all -u /config/cron/* /etc/cron.d

# Update abc user with provided PUID and PGID.
[ -z "$PUID" ] || /usr/sbin/usermod -o -u $PUID abc
[ -z "$PGID" ] || /usr/sbin/groupmod -o -g $PGID abc

# Update the provided time zone in the global environment file.
# This allows cron to pass the time zone to apps it runs.
[ -z "$TZ" ] || /usr/bin/sed -i'' /etc/environment -e "s#^TZ=.*#TZ=$TZ#g"

# Start supervisor, which starts cron any other workers.
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
